
# POST http://localhost:8080/register
# Content-Type: application/json

# {
#     "username" : "minhhieu",
#     "password" : "d4dfdf",
#     "email" : "19021274@vnu.edu.vn",
#     "fullname" : "Dang Minh Hieu",
#     "dob" : "2001-01"
# }

# POST http://localhost:8080/login
# Content-Type: application/json

# {
#     "account" : "minhhieu",
#     "password" : "d4dfdf"
# }

# PATCH http://localhost:8080/update-userInfo
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRpZW1xdXluaCIsImVtYWlsIjoiMTkwMjEyNzRAdm51LmVkdS52biIsImZ1bGxuYW1lIjoiRGFuZyBNaW5oIEhpZXUiLCJpYXQiOjE2NTk0MjgxNzIsImV4cCI6MTY1OTUxNDU3Mn0.o-j-wiVOlSeS_UDcBEL5okTIybYHe-IYHV2a4z5p6VI
# Content-Type: application/json

# {
#     "dob" : "2000-01"
# }

# POST http://localhost:8080/activate
# Content-Type: application/json

# {
#     "email" : "19021274@vnu.edu.vn",
#     "otp" : 4734
# }

# POST http://localhost:8080/album
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pbmhoaWV1IiwiZW1haWwiOiIxOTAyMTI3NEB2bnUuZWR1LnZuIiwiZnVsbG5hbWUiOiJEYW5nIE1pbmggSGlldSIsImlhdCI6MTY1OTQ5MzMzNiwiZXhwIjoxNjU5NTc5NzM2fQ.0GXi-MNk8UBmsRUnxkaNArXl8OZATqpxxWsxZtuI-HU
# Content-Type: application/json

# {
#     "albumname" : "VMOOO",
#     "description" : "cong ty"
# }

# PUT http://localhost:8080/album/62e9f0e0da32f9ea30e6c5e5
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pbmhoaWV1IiwiZW1haWwiOiIxOTAyMTI3NEB2bnUuZWR1LnZuIiwiZnVsbG5hbWUiOiJEYW5nIE1pbmggSGlldSIsImlhdCI6MTY1OTQ5MzMzNiwiZXhwIjoxNjU5NTc5NzM2fQ.0GXi-MNk8UBmsRUnxkaNArXl8OZATqpxxWsxZtuI-HU
# Content-Type: application/json

# {
#     "albumname" : "VMO",
#     "description" : "cong doan"
# }

# DELETE http://localhost:8080/album/62e9e1fc04ba869ccdb92203
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pbmhoaWV1IiwiZW1haWwiOiIxOTAyMTI3NEB2bnUuZWR1LnZuIiwiZnVsbG5hbWUiOiJEYW5nIE1pbmggSGlldSIsImlhdCI6MTY1OTQ5MzMzNiwiZXhwIjoxNjU5NTc5NzM2fQ.0GXi-MNk8UBmsRUnxkaNArXl8OZATqpxxWsxZtuI-HU
# Content-Type: application/json

